services:
  mysql:
    image: mysql:8.4
    container_name: tadda-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tadda_db
    ports:
      - "3307:3306"
    volumes:
      - tadda_mysql_data:/var/lib/mysql

volumes:
  tadda_mysql_data: