#spring.application.name=tadda-backend
spring.datasource.url=jdbc:mysql://localhost:3307/tadda_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=tadda-local-development-secret-key-2026-change-this-before-production-123456
jwt.expiration=86400000

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET}